[2024-07-08T16:21:36.527+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T16:21:36.561+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_store.nds-load manual__2024-07-08T16:18:08.118541+00:00 [queued]>
[2024-07-08T16:21:36.570+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_store.nds-load manual__2024-07-08T16:18:08.118541+00:00 [queued]>
[2024-07-08T16:21:36.571+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-08T16:21:36.587+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): nds-load> on 2024-07-08 16:18:08.118541+00:00
[2024-07-08T16:21:36.594+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=527) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-08T16:21:36.596+0000] {standard_task_runner.py:63} INFO - Started process 529 to run task
[2024-07-08T16:21:36.596+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_store', 'nds-load', 'manual__2024-07-08T16:18:08.118541+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/etl_store.py', '--cfg-path', '/tmp/tmpd3km8q78']
[2024-07-08T16:21:36.598+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask nds-load
[2024-07-08T16:21:36.659+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_store.nds-load manual__2024-07-08T16:18:08.118541+00:00 [running]> on host a58d746d8a30
[2024-07-08T16:21:36.762+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_store' AIRFLOW_CTX_TASK_ID='nds-load' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T16:18:08.118541+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-08T16:18:08.118541+00:00'
[2024-07-08T16:21:36.763+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T16:21:36.811+0000] {base.py:84} INFO - Using connection ID 'postgres-netology' for task execution.
[2024-07-08T16:21:36.884+0000] {base.py:84} INFO - Using connection ID 'postgres-netology' for task execution.
[2024-07-08T16:21:36.949+0000] {base.py:84} INFO - Using connection ID 'postgres-netology' for task execution.
[2024-07-08T16:21:37.006+0000] {base.py:84} INFO - Using connection ID 'postgres-netology' for task execution.
[2024-07-08T16:21:37.064+0000] {base.py:84} INFO - Using connection ID 'postgres-netology' for task execution.
[2024-07-08T16:21:37.116+0000] {base.py:84} INFO - Using connection ID 'postgres-netology' for task execution.
[2024-07-08T16:21:37.166+0000] {base.py:84} INFO - Using connection ID 'postgres-netology' for task execution.
[2024-07-08T16:21:37.286+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T16:21:37.287+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/etl_store/extract_data_nds.py", line 75, in dim_nds
    fact_sales(df, hook)
  File "/opt/airflow/dags/tasks/etl_store/extract_data_nds.py", line 63, in fact_sales
    df['payment'] = df['payment'].map({v+1: k for k, v in payment.items()})
                                       ~^~
TypeError: can only concatenate str (not "int") to str
[2024-07-08T16:21:37.305+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_store, task_id=nds-load, run_id=manual__2024-07-08T16:18:08.118541+00:00, execution_date=20240708T161808, start_date=20240708T162136, end_date=20240708T162137
[2024-07-08T16:21:37.318+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 53 for task nds-load (can only concatenate str (not "int") to str; 529)
[2024-07-08T16:21:37.332+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-08T16:21:37.346+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-07-08T16:21:37.361+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-08T16:21:37.367+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
