[2024-07-08T15:21:14.552+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T15:21:14.598+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_store.nds-load manual__2024-07-08T15:21:11.394292+00:00 [queued]>
[2024-07-08T15:21:14.612+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_store.nds-load manual__2024-07-08T15:21:11.394292+00:00 [queued]>
[2024-07-08T15:21:14.613+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-08T15:21:14.630+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): nds-load> on 2024-07-08 15:21:11.394292+00:00
[2024-07-08T15:21:14.640+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=69) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-08T15:21:14.642+0000] {standard_task_runner.py:63} INFO - Started process 71 to run task
[2024-07-08T15:21:14.641+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_store', 'nds-load', 'manual__2024-07-08T15:21:11.394292+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/etl_store.py', '--cfg-path', '/tmp/tmpp1nqe2lz']
[2024-07-08T15:21:14.644+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask nds-load
[2024-07-08T15:21:14.710+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_store.nds-load manual__2024-07-08T15:21:11.394292+00:00 [running]> on host 3dcb0f2196e2
[2024-07-08T15:21:14.851+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_store' AIRFLOW_CTX_TASK_ID='nds-load' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T15:21:11.394292+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-08T15:21:11.394292+00:00'
[2024-07-08T15:21:14.853+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T15:21:14.896+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T15:21:14.897+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/etl_store/extract_data_nds.py", line 66, in dim_nds
    df = pd.read_csv(csv_file_store_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/supermarket_sales - Sheet1.csv'
[2024-07-08T15:21:14.925+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_store, task_id=nds-load, run_id=manual__2024-07-08T15:21:11.394292+00:00, execution_date=20240708T152111, start_date=20240708T152114, end_date=20240708T152114
[2024-07-08T15:21:14.941+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 20 for task nds-load ([Errno 2] No such file or directory: 'datasets/supermarket_sales - Sheet1.csv'; 71)
[2024-07-08T15:21:14.977+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-08T15:21:14.992+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-07-08T15:21:15.009+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-08T15:21:15.014+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
