[2024-07-08T15:16:17.336+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: etl_store.nds-load scheduled__2024-07-05T01:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
